export const PropertyType = {
  SINGLE_FAMILY_HOME: 'Single-Family Home',
  TOWNHOME: 'Townhome',
  BUNGALOW: 'Bungalow',
  RANCH: 'Ranch',
  CONDOS: 'Condos',
  VICTORIAN: 'Victorian',
  COLONIAL: 'Colonial',
  CONTAINER_HOME: 'Container Home',
  SPLIT_LEVEL: 'Split Level',
  HOUSEBOAT: 'Houseboat',
  MEDITERRANEAN: 'Mediterranean',
  TUDOR: 'Tudor',
  CRAFTSMAN: 'Craftsman',
  TINY_HOUSE: 'Tiny House',
  CO_OP: 'Co-op',
  CABIN: 'Cabin',
  APARTMENT: 'Apartment',
  MANUFACTURED_HOME: 'Manufactured Home',
  MOBILE_HOME: 'Mobile Home',
  MID_CENTURY_MODERN: 'Mid-Century Modern Style',
  CAPE_COD: 'Cape Cod',
  FARMHOUSE: 'Farmhouse',
  MANSION: 'Mansion',
};

export const ListingType = {
  SALE: 'Sale',
  RENT: 'Rent',
};
